apiVersion: v1
kind: Service
metadata:
  name: load-balancer
  labels:
    app: san-express-app
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    app: san-express-app
  type: LoadBalancer
