apiVersion: v1
kind: Service
metadata:
  name: san-express-service
  labels:
    app: san-express-app
spec:
  type: NodePort
  selector:
    app: san-express-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
