name: Sandesh Node JS Express-APP

on:
  push:
    branches:
      - main

jobs:
  say-hello:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]  # You can also use 16.x or 20.x as needed

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set short SHA
        id: vars
        run: echo "sha_short=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_OUTPUT

      - name: Say Hello
        run: echo "Hello, world! sha is ${{ steps.vars.outputs.sha_short}}"

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci  # or `npm install` if you don’t use a lockfile

      #- name: Run tests
      #  run: npm test

      #- name: Build app
      #  run: npm run build

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-node-app:${{ steps.vars.outputs.sha_short}} .

      - name: Push Docker image into Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-node-app:${{ steps.vars.outputs.sha_short}}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --region $AWS_REGION --name san-test-cluster

      - name: Apply Deployment
        run: kubectl apply -f Deployment.yaml    

      - name: Apply service
        run: kubectl apply -f Service.yaml
      
